### ISSUE TITLE
API design problem - File required instead of inputstream

### ISSUE THREAD

**Issue by ahtremblay** [phaxio/phaxio-java#6]
The Fax.send method requires a list of file, instead of a general inputstream. My application holds the data on Amazon S3. To use this API, I now have to create a temporary file on the local disk, just to pass it to the method and then immediately delete the file. Very inefficient.

**Comment by jnankin** [comment]
Can you use string_data to pass us the URL of your file on S3?

For instance, you should be able to do:

options.put("string_data", "http://YOUR_URL");
options.put("string_data_type", "url");
...and then pass options to your send() call.

**Comment by ahtremblay** [comment]
Hi, thanks for the response. The S3 files are private and do not have a public url.

**Comment by jnankin** [comment]
If that's the case, there must be some system that can access the file data and can POST it to Phaxio.  Even if you pass an InputStream to the library, the library would have to download the file in order to POST its contents to Phaxio.  

Are you saying you'd like the library to handle this internally somehow as opposed to you having to do it outside the library?  Computationally it would be the same operations, but it would move this burden to the library instead of your code?

**Comment by ahtremblay** [comment]
In HttpRequestHelper, a file param is posted with the following. I was under the impression that the boundary / double-hyphen system is a in-house format. If that is correct, I believe it would be more appropriate for the library to handle it.

        dos.writeBytes(twoHyphens + boundary + lineEnd);
        dos.writeBytes("Content-Disposition: form-data; name=\"" + key + "\";filename=\"" + file.getName() + "\"" + lineEnd);
        dos.writeBytes(lineEnd);

        FileInputStream fileInputStream = new FileInputStream(file);
        bytesAvailable = fileInputStream.available();
        bufferSize = Math.min(bytesAvailable, maxBufferSize);
        buffer = new byte[bufferSize];
        bytesRead = fileInputStream.read(buffer, 0, bufferSize);

        while (bytesRead > 0) {
            dos.write(buffer, 0, bufferSize);
            bytesAvailable = fileInputStream.available();
            bufferSize = Math.min(bytesAvailable, maxBufferSize);
            bytesRead = fileInputStream.read(buffer, 0, bufferSize);
        }

        dos.writeBytes(lineEnd);
        dos.writeBytes(twoHyphens + boundary + twoHyphens + lineEnd);

**Comment by jnankin** [comment]
So we can definitely work on accepting InputStreams.  I have most of this code written.  The issue is really that we need a filename to pass to the API and a content type.  How would we detect the content type from the input stream?  Should we accept URLs and then create the input stream from that?  If the library accessed a URL it would be able to obtain the content type.  

Not sure how you're getting a stream to your private s3 data.

**Comment by ahtremblay** [comment]
Hi. The function 

s3object.getS3InputStream will give me an inputStream that I can pass to your api.

I suggest a HashMap<String, InputStream>, where the key of the map is the filename.

**Comment by ahtremblay** [comment]
New info :

I just remembered Java determines the content type from the extension of the file name by comparing it to a predefined list. So the best way would likely be to let the client specify the content type.
